/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package euler

import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory

class Euler1to10Test {

    @TestFactory
    fun euler001Test() = listOf(
        1000 to 233168,
        49 to 543,
        8456 to 16687353,
        19564 to 89301183
    )
        .map { (input, expected) ->
            DynamicTest.dynamicTest("the sum of multiples of 3 or 5 below $input is $expected") {
                Assertions.assertEquals(expected, euler001(input))
            }
        }

    @TestFactory
    fun euler002Test() = listOf(
        8 to 10,
        10 to 10,
        34 to 44,
        60 to 44,
        1000 to 798,
        100000 to 60696,
        4000000 to 4613732
    )
        .map { (input, expected) ->
            DynamicTest.dynamicTest("the sum of even Fibonacci numbers below $input is $expected") {
                Assertions.assertEquals(expected, euler002(input))
            }
        }

    @TestFactory
    fun euler003Test() = listOf(
        2 to 2,
        3 to 3,
        5 to 5,
        7 to 7,
        8 to 2,
        13195 to 29,
        600851475143 to 6857
    )
        .map { (input, expected) ->
            DynamicTest.dynamicTest("the largest prime factor of $input is $expected") {
                Assertions.assertEquals(expected.toLong(), euler003(input.toLong()))
            }
        }

    @TestFactory
    fun euler004Test() = listOf(
        2 to 9009,
        3 to 906609
    )
        .map { (input, expected) ->
            DynamicTest.dynamicTest("the largest palindrome made from the product of two n-digit numbers") {
                Assertions.assertEquals(expected, euler004(input))
            }
        }

    @TestFactory
    fun euler005Test() = listOf(
        5 to 60,
        7 to 420,
        10 to 2520,
        13 to 360360,
        20 to 232792560
    )
        .map { (input, expected) ->
            DynamicTest.dynamicTest("smallest positive number that is evenly divisible by all of the numbers from 1 to $input is $expected") {
                Assertions.assertEquals(expected, euler005(input))
            }
        }
}
