/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *   										1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
package euler

/**
 * Solution of second Euler problem.
 * Returns the sum of even Fibonacci numbers below  [input].
 */
fun euler002(input: Int): Int {
    var sum = 0
    val fib = arrayOf<Int>(0, 1, 1)

    while (fib[2] <= input) {
        if (fib[2] % 2 == 0) {
            sum += fib[2]
        }
        fib[0] = fib[1]
        fib[1] = fib[2]
        fib[2] = fib[0] + fib[1]
    }
    return sum
}
